name: bpytop
adopt-info: bpytop
summary: A Python-based resource monitor for your terminal. 
description: |
  Resource monitor that shows usage and stats for processor, memory, disks, network and processes.
  Python port of bashtop
  
    - Easy to use, with a game inspired menu system.
    - Fast and "mostly" responsive UI with UP, DOWN keys process selection.
    - Function for showing detailed stats for selected process.
    - Ability to filter processes.
    - Easy switching between sorting options.
    - Send SIGTERM, SIGKILL, SIGINT to selected process.
    - UI menu for changing all config file options.
    - Auto scaling graph for network usage.
    - Shows message in menu if new version is available
    - Shows current read and write speeds for disks
    - Multiple data collection methods which can be switched if running on Linux
  
  Once installed, run the following commands so the snap will function as intended:
    sudo snap connect bpytop:mount-observe
    sudo snap connect bpytop:network-control
    sudo snap connect bpytop:hardware-observe
    sudo snap connect bpytop:system-observe
    sudo snap connect bpytop:process-control
    sudo snap connect bpytop:physical-memory-observe
    
  You can make changes to the configs and even add themes here:
    ~/snap/bashtop/current/.config/bpytop
    
license: Apache-2.0

base: core18
grade: stable
confinement: strict

apps:
  bpytop:
    command: bpytop
    environment:
      LC_ALL: C.UTF-8
    plugs:
      - mount-observe
      - network-control
      - process-control
      - system-observe
      - hardware-observe
      - network
      - physical-memory-observe
      - home
      
parts:
  bpytop:
    source: https://github.com/aristocratos/bpytop
    plugin: python
    python-version: python3
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//')"
    override-build: |
      make install PREFIX=/usr DESTDIR=$SNAPCRAFT_PART_INSTALL
      
    build-packages:
      - python3
      - python3-psutil
      - python3-pip
      - python-distutils-extra
      
    stage-packages:
      - python3-psutil
