name: bpytop
adopt-info: bpytop
summary: A Python-based resource monitor for your terminal. 
description: |
  Resource monitor that shows usage and stats for processor, memory, disks, network and processes.
  Python port of bashtop
  
    - Easy to use, with a game inspired menu system.
    - Fast and "mostly" responsive UI with UP, DOWN keys process selection.
    - Function for showing detailed stats for selected process.
    - Ability to filter processes.
    - Easy switching between sorting options.
    - Send SIGTERM, SIGKILL, SIGINT to selected process.
    - UI menu for changing all config file options.
    - Auto scaling graph for network usage.
    - Shows message in menu if new version is available
    - Shows current read and write speeds for disks
    - Multiple data collection methods which can be switched if running on Linux
  
  Once installed, run the following commands so the snap will function as intended:
    sudo snap connect bpytop:mount-observe
    sudo snap connect bpytop:network-control
    sudo snap connect bpytop:hardware-observe
    sudo snap connect bpytop:system-observe
    sudo snap connect bpytop:process-control
    sudo snap connect bpytop:physical-memory-observe
    
  You can make changes to the configs and even add themes here:
    ~/snap/bashtop/current/.config/bpytop
    
license: Apache-2.0

base: core20
grade: stable
confinement: strict

apps:
  bpytop:
    command: bpytop
    environment:
      LC_ALL: C.UTF-8
    plugs:
      - mount-observe
      - network-control
      - process-control
      - system-observe
      - hardware-observe
      - network
      - physical-memory-observe
parts:     
  psutil:
    source: https://github.com/giampaolo/psutil.git
    plugin: nil
    override-pull: |
      snapcraftctl pull
      git checkout `git describe --tags --abbrev=0`
    override-build: |
      python3 setup.py install --install-layout=deb --root=$SNAPCRAFT_PART_INSTALL --prefix=/usr
      find $SNAPCRAFT_PART_INSTALL -type d -name __pycache__ -print0 | xargs -0 rm -rf
      find $SNAPCRAFT_PART_INSTALL -type f -name *.so -print0 | xargs -0 strip -s
    build-packages: [python3-all-dev, python3-setuptools]

  bpytop:
    source: https://github.com/aristocratos/bpytop.git
    plugin: nil
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//')"
    override-build: make install PREFIX=/usr DESTDIR=$SNAPCRAFT_PART_INSTALL
    stage-packages: [python3-all]
    prime:
      - -bin
      - -usr/share/doc
      - -usr/share/man
